#!/bin/bash
# Bash wrappers for docker run commands
# Proudly learned, and copied a lot from https://github.com/jessfraz/dotfiles/blob/master/.dockerfunc

#
# Helper Functions
#
del_stopped(){
	local name=$1
	local state
	state=$(docker inspect --format "{{.State.Running}}" "$name" 2>/dev/null)

	if [[ "$state" == "false" ]]; then
		docker rm "$name"
	fi
}

#
# Container Aliases
#
node(){
  del_stopped node

  docker run -it --rm \
    --volume "${PWD}":/app \
		--name node \
    node bash
}